# Generated by Django 3.0 on 2019-12-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageinfo',
            name='date',
            field=models.DateField(),
        ),
    ]
